services:
  - type: web
    name: sui-discord-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CHANNEL_ID
        sync: false
      - key: SUI_PRIVATE_KEY
        sync: false
      - key: SUI_TARGET_ADDRESS
        sync: false
      - key: RPC_URL
        sync: false
      - key: WATCHED_ADDRESSES
        sync: false
      - key: POLL_INTERVAL
        sync: false
