services:
  - type: web
    name: sui-discord-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DISCORD_CHANNEL_ID
        sync: false
      - key: SUI_PRIVATE_KEY
        sync: false
      - key: SUI_TARGET_ADDRESS
        sync: false
      - key: RPC_URL
        value: https://rpc-mainnet.suiscan.xyz/
      - key: POLL_INTERVAL
        value: "1"
      - key: WATCHED_ADDRESSES
        value: >
          {
            "Ví Neuter": "0x98101c31bff7ba0ecddeaf79ab4e1cfb6430b0d34a3a91d58570a3eb32160682",
            "Khiêm Nguyễn":"0xfb4dd4169b270d767501b142df7b289a3194e72cbadd1e3a2c30118693bde32c"
          }
