services:
  - type: web
    name: sui-discord-bot
    runtime: python
    pythonVersion: 3.11        # ← ép Render dùng 3.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
